name: 'Setup Atom and APM'
description: 'Setup Atom and APM'
inputs:
  channel:
    description: 'Channel'
    required: true
    default: 'Stable'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'green'
